services:
  frontend:
    build: Studyrats-frontend
    container_name: studyrats-frontend
    restart: always
    ports:
      - "8081:80"

  db:
    image: postgres:17
    container_name: studyrats-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: StudyRats_backend
    container_name: studyrats-backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEY_SECRET: ${KEY_SECRET}
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
